// ============================================================
//  js/firebase.js  — Firebase init & all database operations (Realtime Database Version)
//  Do NOT edit this file. Change CONFIG in js/config.js only.
// ============================================================

import { initializeApp }                          from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js';
import { getDatabase, ref, push, set, get, update, remove, query, orderByChild, equalTo, limitToLast, runTransaction, onValue } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js';

let db;

// ── Init ────────────────────────────────────────────────────
export function initFirebase() {
  const app = initializeApp(CONFIG.FIREBASE);
  db = getDatabase(app);
  window.__db = db;
  console.log('[Firebase] Connected (Realtime Database)');
  return db;
}

// ── Save article ────────────────────────────────────────────
export async function saveArticle(article) {
  if (!db) throw new Error('Firebase not initialized');
  const articlesRef = ref(db, 'articles');
  const newArticleRef = push(articlesRef);
  const data = {
    ...article,
    id: newArticleRef.key,
    timestamp : article.timestamp || Date.now(),
    views     : 0,
    published : true,
  };
  await set(newArticleRef, data);
  return newArticleRef.key;
}

// ── Load articles (all, or by category) ─────────────────────
export async function loadArticles({ category = null, max = 50 } = {}) {
  if (!db) return [];
  try {
    const articlesRef = ref(db, 'articles');
    // Query last max articles ordered by timestamp
    let q = query(articlesRef, orderByChild('timestamp'), limitToLast(max));
    const snap = await get(q);
    if (!snap.exists()) return [];

    const list = [];
    snap.forEach(child => {
      list.push({ id: child.key, ...child.val() });
    });
    // Reverse because limitToLast gets the latest in ascending order
    list.reverse();

    if (category) {
      return list.filter(a => a.category === category);
    }
    return list;
  } catch (e) {
    console.warn('[Firebase] Load error:', e.message);
    return [];
  }
}

// ── Get single article ───────────────────────────────────────
export async function getArticle(id) {
  if (!db) return null;
  const snap = await get(ref(db, `articles/${id}`));
  return snap.exists() ? { id: snap.key, ...snap.val() } : null;
}

// ── Delete article ───────────────────────────────────────────
export async function deleteArticle(id) {
  if (!db) return;
  await remove(ref(db, `articles/${id}`));
}

// ── Update article ───────────────────────────────────────────
export async function updateArticle(id, data) {
  if (!db) return;
  await update(ref(db, `articles/${id}`), data);
}

// ── Check if article already exists (avoid duplicates) ───────
export async function articleExists(title) {
  if (!db) return false;
  try {
    const isSeedKey = title.startsWith('seed_');
    const childField = isSeedKey ? '_seedKey' : 'title';
    const q = query(
      ref(db, 'articles'),
      orderByChild(childField),
      equalTo(title),
      limitToLast(1)
    );
    const snap = await get(q);
    return snap.exists();
  } catch (e) {
    console.warn('[Firebase] Server-side check failed, falling back to client-side filter:', e.message);
    try {
      const snap = await get(ref(db, 'articles'));
      if (!snap.exists()) return false;
      const isSeedKey = title.startsWith('seed_');
      let found = false;
      snap.forEach(child => {
        const val = child.val();
        if (isSeedKey) {
          if (val._seedKey === title) found = true;
        } else {
          if (val.title === title) found = true;
        }
      });
      return found;
    } catch {
      return false;
    }
  }
}

// ── Visitor Counter ──────────────────────────────────────────
export function setupVisitorCounter(callback) {
  if (!db) return;
  const visitorRef = ref(db, 'visitor_count');

  // Prevent refresh count by using sessionStorage
  if (!sessionStorage.getItem('newsbuzz_visited')) {
    sessionStorage.setItem('newsbuzz_visited', 'true');
    runTransaction(visitorRef, (currentValue) => {
      return (currentValue || 0) + 1;
    });
  }

  // Listen to changes and update the UI via callback
  onValue(visitorRef, (snapshot) => {
    const count = snapshot.val() || 0;
    callback(count);
  });
}

export { db };
